### ISSUE TITLE
Add defaults for ranger$mtry and ranger$min.node.size

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#15]
There are some problems with the current parameter_ranges default-values.
Here are some examples of the problems:
- In the OpenML database, the `ranger` parameter `respect.unordered.factors` is boolean. In the database, the only value is `TRUE` which implies the default value is `FALSE` and we could fill that in. The problem is, that in `parameter_ranges` the default is `ignore` instead of `FALSE`. Even worse, the parameter `respect.unordered.factors` has three factor levels in parameter_ranges, making the `boolean` representation in the OpenML unfit.
- In the OpenML database, some runs (of `ranger`, again) have not set the parameter `mtry`, implying that these runs have been made with the default value of `mtry`, although no default value is set for mtry. There is no default for `mtry` because in the mlr definition contains different parameter definitions, eg. the `mtry` parameter isn't even defined there.

These problems are caused by two things:
- Different base data: mlr parameter definitions and openml-bot parameter definitions differ somewhat in parameter names and allowed values.
- Unknown conversion: Somewhere, the conversion of openml-bot parameters to mlr parameters must happen. It is unclear where this is.

Until these problems are resolved, it is unclear how to derive appropriate default values for the parameters in the OpenML database.

**Comment by jakob-r** [comment]
* **ranger, repsect.unordered.factors** the parameter changed in some version. We still only use TRUE/FALSE, right? See here for details: https://rdrr.io/cran/ranger/man/ranger.html.
This means we only have to change that in the preprocessing to the old versions defaults
* **ranger, mtry** The default is data dependent and you can find it in the documentation. Look there for the meaning. In OMLBots mtry is a value between 0 and 1, defining the share instead of the absolute number. See [here](https://github.com/ja-thomas/OMLbots/blob/039ac0bb715c05affe4cad2f6f933a922d5904c5/R/botCallWrapper.R#L35). We should also only accept values between 0 and 1. If the value is missing it means we hit the default. This is really unpracitcal. Strangely they are also not handled [here](https://github.com/ja-thomas/OMLbots/blob/02f64a48ab45215700ab3c1ef0566c9fc3ac5a74/snapshot_database/database_extraction.R#L89). But the information about the number of features in the dataset for the given run should be in the database.

**Comment by mboecker** [comment]
Because of [this](https://github.com/ja-thomas/OMLbots/blob/039ac0bb715c05affe4cad2f6f933a922d5904c5/R/botCallWrapper.R#L37), this also applies to min.node.size, right?

**Comment by mboecker** [comment]
At least those two seem like the only parameters we need to special-case.

**Comment by mboecker** [comment]
> ranger, repsect.unordered.factors the parameter changed in some version. We still only use TRUE/FALSE, right? See here for details: https://rdrr.io/cran/ranger/man/ranger.html.
This means we only have to change that in the preprocessing to the old versions defaults

This is done in 2592f40c14637b1dbbdc3d60574a17b882128ace.

**Comment by mboecker** [comment]
> ranger, mtry The default is data dependent and you can find it in the documentation. Look there for the meaning. In OMLBots mtry is a value between 0 and 1, defining the share instead of the absolute number. See here. We should also only accept values between 0 and 1. If the value is missing it means we hit the default. This is really unpracitcal. Strangely they are also not handled here. But the information about the number of features in the dataset for the given run should be in the database.

This is blocked on #25.

**Comment by mboecker** [comment]
What are we trying to do?
It states [here](https://mlr-org.github.io/mlr-tutorial/release/html/integrated_learners/), that

> Default for mtry is the floor of square root of number of features in task.
> Default for min.node.size is 1 for classification and 10 for probability estimation.

Should we do that?

**Comment by jakob-r** [comment]
I think we solved that, right? Please close if so.

**Comment by jakob-r** [comment]
can you get all non missing values for `min.node.size` and check if there is some pattern?

Otherwise we just have to assume that sometimes they got deleted and sometimes not? Maybe due to a change in the saving mechanism?

**Comment by mboecker** [comment]
Unfortunately there seems to be no pattern.

**Comment by jakob-r** [comment]
Well - if there is no pattern in the non missing values it's actually a good sign.
