### ISSUE TITLE
Svm repair

### ISSUE THREAD

**Issue by mboecker** [mboecker/lookup-server#83]

**Comment by jakob-r** [comment]
- what happens if we ask for kernel = linear and degree = 3. should be an error
- are those runs in the DB used that contain infeasible vales. e.g. asking over the api for kernel = "radial", cost = 24.9996 and gamma = 0.00821006 should return the AUC of rid 2127568 even though it has degree = 3 because degree has no meaning in this context.

**Comment by mboecker** [comment]
> are those runs in the DB used that contain infeasible vales. e.g. asking over the api for kernel = "radial", cost = 24.9996 and gamma = 0.00821006 should return the AUC of rid 2127568 even though it has degree = 3 because degree has no meaning in this context. (see #65)

The database now contains NA for any kernel different than polynomial.

**Comment by mboecker** [comment]
It appears to be necessary to set "degree" on the user-side, even though it carries no value... We should check why a param.set without degree isn't feasible

**Comment by jakob-r** [comment]
I tested it for this value and it worked.
