### ISSUE TITLE
Data Overview Table

### ISSUE THREAD

**Issue by jakob-r** [mboecker/lookup-server#87]
Table with columns:
Data Id, Runs for svm in DB, Runs for knn in DB ... , Baseline Performances (should be written somewhere), p (number of features) , n (observations)

Can be a API Request.

* Are Datasets of OpenML100 Missing?
* Do we have additional Datasets?

Cross check with:
https://arxiv.org/abs/1708.03731
https://docs.openml.org/benchmark/#openml100
https://arxiv.org/abs/1806.10961

**Comment by mboecker** [comment]
```
> get_task_metadata(3)
$nrow
[1] 3196

$ncol
[1] 36
```

I've only got task 3 loaded at the moment, but I found my first discrepancy. The OpenML 100 Paper [1] lists Task 3 to contain 37 features, but the database contains only 36 features. Is this important?

[1]: https://arxiv.org/abs/1708.03731

**Comment by mboecker** [comment]
There are tasks missing from OpenML100
As it seems, we are only supporting the 2-class tasks from OpenML100.

**Comment by mboecker** [comment]
Our database also contains some task_id (like 282, 3892), which is not in any of these papers [1] [2].

We're also missing tasks from the current OpenML 100 List [3], like 15 or 23. That's not our fault though, because the Bot didn't upload any runs of these tasks:

```
MariaDB [openml_native]> SELECT * FROM run WHERE (task_id = 23 OR task_id = 15) AND uploader = 2702;
Empty set (0.00 sec)
```

Please have a look at the merge request https://github.com/mboecker/lookup-server/pull/91, which will give information on every possible task_id on the server.

[1] https://arxiv.org/abs/1708.03731
[2] https://arxiv.org/abs/1806.10961
[3] https://www.openml.org/search?q=tags.tag%3AOpenML100&type=data&table=1&size=100

**Comment by jakob-r** [comment]
> The OpenML 100 Paper 1 lists Task 3 to contain 37 features

Did you use the updated metadata? In OML they used to count all columns (inlcuding the target) as features. Might this be a reason for the difference? I want the value without the target.

> we are only supporting the 2-class tasks from OpenML100

This might be right. Are all the missing tasks multi class problems?

> Our database also contains some task_id (like 282, 3892)

The bot ran on (task 282 => data 53, task 3892 => data 1039) that are not tagged as oml100. We should ignore those runs then.

**Comment by jakob-r** [comment]
> We're also missing tasks from the current OpenML 100 List [3], like 15 or 23.

I guess we should restrict ourselves to the datasets that are mentioned in [2] Table 2.

**Comment by mboecker** [comment]
> Did you use the updated metadata? In OML they used to count all columns (inlcuding the target) as features. Might this be a reason for the difference? I want the value without the target.

It seems to be always off by one. I think your assumption is correct then.
